Update current-federal-non-dotgov.csv
cisagov/scan-target-data pull request #109
Opened 2024-12-05 19:46 UTC by cfx47

PT has requested that we add the following domains so that they show up in their Trustymail and HTTPS reports. I verified they are not currently being picked up in the sources gathered.

goldengateclub.com
presidio-foods.com
presidio-residences.com
presidioofficersclub.com
presidioofsanfrancisco.com
presidioofsanfrancisco.net
presidioofsanfrancisco.org
presidioresidences.com
presidiotours.com
presidiotours.org
presidiotrust.net
presidiotrust.org
presidiotrust.tours
presidiotunneltops.com
presidiotunneltops.org
presidioworkspaces.com
thepresidioofsanfrancisco.com
thepresidioofsanfrancisco.net
thepresidioofsanfrancisco.org
presidiolodging.com
presidiogolf.com
presidiobus.com

#  #

## 🗣 Description ##

## 💭 Motivation and context ##

## 🧪 Testing ##

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

2024-12-05 20:02 UTC, dav3r requested changes
You've got some extra spaces that need to be removed.

2024-12-05 20:02 UTC, dav3r commented on current-federal-non-dotgov.csv
> +goldengateclub.com,Federal Agency - Executive, Presidio Trust,,Washington,DC,
Remove extraneous space:
```suggestion
goldengateclub.com,Federal Agency - Executive,Presidio Trust,,Washington,DC,
```

2024-12-05 20:02 UTC, dav3r commented on current-federal-non-dotgov.csv
> +presidioworkspaces.com,Federal Agency - Executive, Presidio Trust,,Washington,DC,
Remove extraneous spaces:
```suggestion
presidio-foods.com,Federal Agency - Executive,Presidio Trust,,Washington,DC,
presidio-residences.com,Federal Agency - Executive,Presidio Trust,,Washington,DC,
presidiobus.com,Federal Agency - Executive,Presidio Trust,,Washington,DC,
presidiogolf.com,Federal Agency - Executive,Presidio Trust,,Washington,DC,
presidiolodging.com,Federal Agency - Executive,Presidio Trust,,Washington,DC,
presidioofficersclub.com,Federal Agency - Executive,Presidio Trust,,Washington,DC,
presidioofsanfrancisco.com,Federal Agency - Executive,Presidio Trust,,Washington,DC,
presidioofsanfrancisco.net,Federal Agency - Executive,Presidio Trust,,Washington,DC,
presidioofsanfrancisco.org,Federal Agency - Executive,Presidio Trust,,Washington,DC,
presidioresidences.com,Federal Agency - Executive,Presidio Trust,,Washington,DC,
presidiotours.com,Federal Agency - Executive,Presidio Trust,,Washington,DC,
presidiotours.org,Federal Agency - Executive,Presidio Trust,,Washington,DC,
presidiotrust.net,Federal Agency - Executive,Presidio Trust,,Washington,DC,
presidiotrust.org,Federal Agency - Executive,Presidio Trust,,Washington,DC,
presidiotrust.tours,Federal Agency - Executive,Presidio Trust,,Washington,DC,
presidiotunneltops.com,Federal Agency - Executive,Presidio Trust,,Washington,DC,
presidiotunneltops.org,Federal Agency - Executive,Presidio Trust,,Washington,DC,
presidioworkspaces.com,Federal Agency - Executive,Presidio Trust,,Washington,DC,
```

2024-12-05 20:02 UTC, dav3r commented on current-federal-non-dotgov.csv
> +thepresidioofsanfrancisco.org,Federal Agency - Executive, Presidio Trust,,Washington,DC,
Remove extraneous spaces:
```suggestion
thepresidioofsanfrancisco.com,Federal Agency - Executive,Presidio Trust,,Washington,DC,
thepresidioofsanfrancisco.net,Federal Agency - Executive,Presidio Trust,,Washington,DC,
thepresidioofsanfrancisco.org,Federal Agency - Executive,Presidio Trust,,Washington,DC,
```

2024-12-05 21:07 UTC, dav3r commented
@cfx47 Please also update the PR description so that all relevant checkboxes are checked and all non-relevant ones are deleted.  Thanks!

2024-12-06 15:37 UTC, dav3r commented on current-federal-non-dotgov.csv
> +presidioworkspaces.com,Federal Agency - Executive, Presidio Trust,,Washington,DC,
This suggestion was missed - please include it.

2024-12-06 15:54 UTC, dav3r approved these changes
LGTM

I have a couple of notes for the future.  When you commit suggestions, please always replace the default commit message ("Update current-federal-non-dotgov.csv", which is not very helpful) with a more useful message (e.g. "Remove extra spaces").

Also, we **strongly** encourage everyone to follow [these commit message rules](https://cbea.ms/git-commit/#seven-rules) which specify the use of the imperative mood (i.e. you should write "Remove extra spaces" rather than "Remove**d** extra spaces").

2024-12-06 16:33 UTC, jsf9k approved these changes

2024-12-06 20:19 UTC, merged