Add 1 Non-.gov TREAS domain
cisagov/scan-target-data pull request #89
Opened 2023-03-29 16:09 UTC by KeithBonesJr

TREAS has requested that we add tftc-istehdaf.org so that it shows up in their Trustymail and HTTPS reports. I verified it is not currently being picked up in the sources gathered by double checking for its presence in their report. I also received confirmation that this domain is owned and operated by Treasury.

#  #

## 🗣 Description ##

## 💭 Motivation and context ##

## 🧪 Testing ##

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

2023-03-29 16:42 UTC, mcdonnnj commented on current-federal-non-dotgov.csv
> +tftc-istehdaf.org,Federal Agency - Executive,Department of the Treasury,,Washington,DC
This aligns with the other records in this file.

```suggestion
tftc-istehdaf.org,Federal Agency - Executive,Department of the Treasury,,Washington,DC,
```

2023-03-29 17:14 UTC, jsf9k requested changes

2023-03-29 17:14 UTC, jsf9k commented on current-federal-non-dotgov.csv
>  federalalight.com, Federal Agency - Executive,Federal Retirement Thrift Investment Board,,Washington, DC
```suggestion
convergeoperations.com, Federal Agency - Executive,Federal Retirement Thrift Investment Board,,Washington, DC,
federalalight.com, Federal Agency - Executive,Federal Retirement Thrift Investment Board,,Washington, DC,
```

2023-03-29 17:14 UTC, jsf9k commented on current-federal-non-dotgov.csv
>  federalalight.com, Federal Agency - Executive,Federal Retirement Thrift Investment Board,,Washington, DC
May as well fix these two as well.

2023-03-29 17:17 UTC, jsf9k commented
@KeithBonesJr, please note how I filled out the pull request template.  Please try to do this with future pull requests.

2023-03-29 17:19 UTC, mcdonnnj commented on current-federal-non-dotgov.csv
>  federalalight.com, Federal Agency - Executive,Federal Retirement Thrift Investment Board,,Washington, DC
@jsf9k I updated your suggestion to also remove some incorrect leading spaces.

2023-03-29 17:59 UTC, jsf9k approved these changes

2023-03-31 15:32 UTC, dav3r approved these changes
👍

2023-03-31 15:55 UTC, mcdonnnj approved these changes

2023-03-31 16:28 UTC, merged